### ISSUE TITLE
Add fill-in-the-blank README.md for app-starter

### ISSUE THREAD

**Issue by 13rac1** [roundware/roundware-android#1]
The `app-starter` directory needs an example README.md since it will be copied and made into `app` for custom Roundware apps.

Example:
# [App Name]

Copyright [Year] [Organization Name] [Organization Website]

This repository contains the app module for [App Name] based on the [Roundware Android App](https://github.com/roundware/roundware-android])

Development setup:
- git clone https://github.com/roundware/roundware-android
- cd roundware-android
- git clone [App Name Repo] app

Further details are available in the Roundware Android App Readme: https://github.com/roundware/roundware-android/blob/develop/README.md

Learn more about Roundware at: http://www.roundware.org/

**Comment by 13rac1** [comment]
We should also include an additional copy of the GPL in the app-starter directory.

**Comment by 13rac1** [comment]
@hburgund I added the basic Readme from above and a copy of the GPL. What else do we need?

**Comment by hburgund** [comment]
Generally looks good to me.  We should remove the project.txt file from the root directory as that appears to be Rob's notes from early on.
I'm also wondering about what header is required for the source files to apply the license.  In roundware-server, we have a quick two-liner in every code file that refers to the LICENSE etc docs.  Is there a reason we aren't doing that here?  I know different licenses make different recommendations, but it seems to me that this should be done.

**Comment by 13rac1** [comment]
Every source file has that? I bet you are looking at the code in Android Studio and its compressing comments. See: https://github.com/roundware/roundware-android/blob/develop/rwapp/src/main/java/org/roundware/rwapp/RwApplication.java

**Comment by hburgund** [comment]
aha!  I was actually looking at the xml files, which don't appear to have anything, but yes, the Java files have exactly what I was expecting.  Are the xml files somehow not considered "source" and therefore not necessary to have those declarations?  I'm fine with whatever the accepted approach is; just checking.

**Comment by 13rac1** [comment]
I'm not sure the best way to add the GPL notifications to the XML or if it's needed.

I'd like to determine how to leave the option available for people to create/distribute custom no-code-changes XML-only-changes Roundware apps without dealing with publishing their source. I'm not yet sure of the procedure (GPL exception maybe) to do that though.

**Comment by hburgund** [comment]
Agreed.  I don't see a problem leaving it as is for now and figuring out the best approach in the future to accomplish this.

**Comment by 13rac1** [comment]
This is good enough for now with #36
