### ISSUE TITLE
Use Android App action bar

### ISSUE THREAD

**Issue by multidynamic** [roundware/roundware-android#10]
Remove faux actionbar and use standard android one.
Use actionbar-sherlock for old devices or just use standard support menubar items if desired.

:heavy_multiplication_x: A major cosmetic issue

**Comment by hburgund** [comment]
@robknapen this seems related to one of your recent questions about the action bar...not sure removing it is the best solution, but it might be. For now, we want the easiest most standard solution that allows for the open source licenses and a way to quit the app in a menu somewhere on the MainActivity.

**Comment by robknapen** [comment]
Ok, easiest and most standard solution will be to keep the Android ActionBar for the MainActivity. So then this issue can be closed.

**Comment by hburgund** [comment]
ok, closing issue. I wasn't sure if the current implementation was the standard Android ActionBar, but since it is, yes, let's just keep it for now and add back in the licensing menu item and anything else necessary.
