### ISSUE TITLE
Project specific default tags

### ISSUE THREAD

**Issue by multidynamic** [roundware/roundware-android#14]
_eosrei created an issue 2014-12-11_
Halsey says "we need to build a method for including tags with a recording that aren’t hand-selected by the user. case in point, in this app, there needs to be a ‘usertype’ tag for each asset - either ‘museum’ or ‘community’, but clearly we don’t want participants to have to select this manually, as they will all be ‘community’. in the iOS app, I took the easy way out which is to hard-code the community tag (id=153) with the upload, but this clearly isn’t a great long-term approach to this somewhat frequent issue. worth thinking about a better solution, though hard-coding will work near-term."

:x: A major issue

_eosrei REPORTER 2014-12-11_
What about applying them on the server? Or providing them in the "get_config" call?

_Halsey Burgund REPO OWNER 2014-12-12_

Yeah, I agree that this data should originate on the server. We could create another piece of project data called appended_speak_tags or something and have the server add that upon submission. Or perhaps simpler would be, as you say, to include this new field in the get_config response and then the client appends the tag(s) to the add_asset_to_envelope params?
This relates to my "project-data" idea; a method of adding any sort of data to a project and have it automatically be returned in get_config (or its successor api/2 call). More info in this GitHub issue:
https://github.com/hburgund/roundware-server/issues/111

**Comment by 13rac1** [comment]
Closing this issue. Problem should be dealt with server-side.
