### ISSUE TITLE
App slows down?

### ISSUE THREAD

**Issue by multidynamic** [roundware/roundware-android#16]
_eosrei created an issue 2014-12-11_
Halsey reports "app seems to slow down and get less responsive over time somehow? seems very weird; maybe it’s my device"
Halsey Burgund More details on how to reproduce?

:x: A major issue

_Halsey Burgund REPO OWNER 2014-12-11_
Apologies for the vagueness on this one. I will continue to try to see what consistencies exist, but thus far, I open the app and start using it and things are fairly snappy wrt UI responsiveness. But then after I listen and record, then listen again or record twice, it seems as though the snappiness is reduced significantly, particularly in the webviews. It feels like things are not being cleaned up and resources are becoming constrained as a session goes on, but this is purely a guess.
I am using an LG Nexus 4 with very little else installed as this is purely a test device.
I'll report back if I discover more useful and consistent behaviors.

_Matthew Adler 2014-12-11_
In general, webviews are resource hogs. If you suspect the content will always be the same then it's worth it to use a native android layout instead.

_Halsey Burgund REPO OWNER 2014-12-12_
related to my responses on issue #18, we should consider native layout instead if the webviews themselves are the cause of the weirdness (ie not the code inside the webviews or something else).
These views, web or native, will need to remain flexible to configure themselves based on the data returned by get_tags, but I'm sure we could replicate the approach natively. If this issue persists and is consistent, it's likely not worth major debugging/tweaking efforts on the webview approach if the native approach will solve it quicker and more robustly. We can sacrifice the flexibility webviews afford.

**Comment by 13rac1** [comment]
Could this be related to: https://github.com/roundware/roundware-android/issues/23#issuecomment-71141774 Are new Activities created? I had quite the stack of Activities to back out of while testing today.

**Comment by multidynamic** [comment]
@eosrei I doubt this is the cause, unless the Activities have a bunch of busy threads running; hopefully android should kill them before that happens...

@eosrei did it slow down, like Halsey reported?

**Comment by multidynamic** [comment]
Using the Android Device Monitor you can profile the app when you notice in this situation. It may provide some insight to the culprit of this slow down.

**Comment by 13rac1** [comment]
I'm closing this. We don't have information specific to this issue. Create a new issue if/when specific details are available and not covered in existing issues.
