### ISSUE TITLE
Delayed 'move_listener' calls causes delayed voices in audio stream

### ISSUE THREAD

**Issue by 13rac1** [roundware/roundware-android#39]
The Android RW Service starts an audio stream with `request_stream` but is slow to send a `move_listener` update. A `move_listener` call including a GPS lat/long is needed to start the RW Asset playback. The resulting experience by the user is background music, but no audio assets.

You can even reproduce the issue with FakeGPS.
- Start FakeGPS
- Select a location within the de Young sculpture garden near a sculpture (where audio assets exist)
- Start the Roundware app
- Press `listen`
- Wait forever (if you want) and hear no voices.

To get audio:
- Switch back to FakeGPS
- Set a new location (I'm not sure if this is distance from the original location has an effect)
- After a minor delay for buffering, audio assets will start playing back.

Expected: Audio assets start playing as soon as the app is audio stream starts.

Solution: Send a `move_listener` call ASAP after app playback starts?

**Comment by hburgund** [comment]
I agree with the proposed solution.  That said, I'm surprised that a `move_listener` doesn't get sent pretty quickly after `request_stream` is returned naturally since GPS tends to frequently update/refine.  I don't know how it works in Android or what fine-tuning parameters have been set to dictate the GPS behavior in the app, but I suppose if the accuracy isn't set very high, `move_listeners` could be much less frequent.

**Comment by 13rac1** [comment]
FYI When this issue is corrected you'll know it's working right because then you'll encounter this issue on the server :laughing: :sob: https://github.com/roundware/roundware-server/issues/173

**Comment by multidynamic** [comment]
Perhaps the `request_steam` call should include the lat long.

**Comment by 13rac1** [comment]
@multidynamic Yes, it's actually sent, but the data isn't currently handled by the server. Either way, voice/asset playback isn't an issue on iOS right now. It should be less time to fix this issue in Android, than change the Server and iOS.

Should be straightfoward to make a `move_listener` call as soon as the location reporting services have a location.
