### ISSUE TITLE
Inspect Resources

### ISSUE THREAD

**Issue by multidynamic** [roundware/roundware-android#5]
With the new rwapp/app re-org some resources have been misplaced. This ticket is to ensure all resources are accounted for all device resolutions.

:x: A major issue

**Comment by 13rac1** [comment]
There are no high resolution images in this repo. That is on purpose to reduce repo file size.

I'm opening a separate issue for the FAMSF specific images.

**Comment by multidynamic** [comment]
I moved the default backgrounds around to allow for better override in famsf.

**Comment by 13rac1** [comment]
I wasn't sure of the ideal location so I went with something that worked. We don't _need_ more than one image per type in this repo correct?

**Comment by multidynamic** [comment]
Yeah, they're just placeholders, so I think it's fine.
