### ISSUE TITLE
Android client displays webview background

### ISSUE THREAD

**Issue by multidynamic** [roundware/roundware-android#61]
For the Speak and Refine screen the backgrounds should be locations specifiec.

It appears the intention is for the webview to be transparent and for the background to display through it. This does not appear to be happening in Android, a legion of honor background is part of the webview.

**Comment by hburgund** [comment]
I tried making the background of the webview transparent, but that doesn't seem to work in any situation.  The way the iOS app swaps bg images is to pass a variable into the html similarly to how the tags are passed in.

There is a js variable called `roundware_theme` that is used to swap the images.  The app replaces a line of code in the listen.html and speak.html files `/*%roundware_theme%*/` with `roundware_theme = _dy` for example and then the html should do the rest.

I don't think this was ever built into the Android app, but I assume it could be done in the same manner that the tags are passed in by replacing a different html string.

**Comment by multidynamic** [comment]
@hburgund thanks, i will look for this
