### ISSUE TITLE
Show indefinite progress while buffering playback

### ISSUE THREAD

**Issue by multidynamic** [roundware/roundware-android#7]
Sometimes nothing happens when play button is pressed, sometimes a dialog with a indefinite progress is shown, sometimes nothing.
**Fix by always showing the dialog, or changing the button image to an intermediary state.**

:exclamation: A critical issue

**Comment by multidynamic** [comment]
I personally like an busy/greyed icon instead of the dialog. Dialogs annoy me and I think most users. If you are going to go the icon route, the icon should replace the play button and be obvious to indicate the action is in-progress.

**Comment by 13rac1** [comment]
Turning the play/pause button into a spinning circle icon would a great solution.

**Comment by multidynamic** [comment]
I noticed that button mashing the play button will put the app into a locked hanging state.
